<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /src/contrib/Archive/Interpol.T</title>
 </head>
 <body>
<h1>Index of /src/contrib/Archive/Interpol.T</h1>
  <table>
   <tr><th valign="top"><img src="/icons/blank.gif" alt="[ICO]"></th><th><a href="?C=N;O=D">Name</a></th><th><a href="?C=M;O=A">Last modified</a></th><th><a href="?C=S;O=A">Size</a></th><th><a href="?C=D;O=A">Description</a></th></tr>
   <tr><th colspan="5"><hr></th></tr>
<tr><td valign="top"><img src="/icons/back.gif" alt="[PARENTDIR]"></td><td><a href="/src/contrib/Archive/">Parent Directory</a></td><td>&nbsp;</td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/compressed.gif" alt="[   ]"></td><td><a href="Interpol.T_1.0.tar.gz">Interpol.T_1.0.tar.gz</a></td><td align="right">2012-02-01 12:13  </td><td align="right">895K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/compressed.gif" alt="[   ]"></td><td><a href="Interpol.T_2.0.tar.gz">Interpol.T_2.0.tar.gz</a></td><td align="right">2012-07-17 11:59  </td><td align="right">886K</td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/compressed.gif" alt="[   ]"></td><td><a href="Interpol.T_2.1.tar.gz">Interpol.T_2.1.tar.gz</a></td><td align="right">2012-12-20 12:42  </td><td align="right">889K</td><td>&nbsp;</td></tr>
   <tr><th colspan="5"><hr></th></tr>
</table>
<address>Apache Server at cran.r-project.org Port 443</address>
</body></html>
