<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>CRAN - Package Interpol.T</title>
<link rel="stylesheet" type="text/css" href="../../CRAN_web.css" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="DC.identifier" content="https://CRAN.R-project.org/package=Interpol.T" />
<meta name="DC.publisher" content="Comprehensive R Archive Network (CRAN)" />
<meta name="og:title" content="Interpol.T: Hourly interpolation of multiple temperature daily series" />
<meta name="og:description" content="Hourly interpolation of daily minimum and maximum temperature series. Carries out interpolation on multiple series ad once. Requires some hourly series for calibration (alternatively can use default calibration table)." />
<meta name="og:image" content="https://CRAN.R-project.org/CRANlogo.png" />
<meta name="og:type" content="website" />
<meta name="og:url" content="https://CRAN.R-project.org/package=Interpol.T" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@_R_Foundation" />
<style type="text/css">
  table td { vertical-align: top; }
</style>
</head>
<body>
<h2>Interpol.T: Hourly interpolation of multiple temperature daily series</h2>
<p>Hourly interpolation of daily minimum and maximum temperature
    series. Carries out interpolation on multiple series ad once. Requires some
    hourly series for calibration (alternatively can use default calibration
    table).</p>
<table summary="Package Interpol.T summary">
<tr>
<td>Version:</td>
<td>2.1.1</td>
</tr>
<tr>
<td>Depends:</td>
<td>R (&ge; 2.10), <a href="../date/index.html">date</a>, <a href="../chron/index.html">chron</a></td>
</tr>
<tr>
<td>Published:</td>
<td>2013-12-03</td>
</tr>
<tr>
<td>Author:</td>
<td>Emanuele Eccel &amp; Emanuele Cordano</td>
</tr>
<tr>
<td>Maintainer:</td>
<td>Emanuele Eccel  &#x3c;&#x65;&#x6d;&#x61;&#x6e;&#x75;&#x65;&#x6c;&#x65;&#x2e;&#x65;&#x63;&#x63;&#x65;&#x6c;&#x20;&#x61;&#x74;&#x20;&#x66;&#x6d;&#x61;&#x63;&#x68;&#x2e;&#x69;&#x74;&#x3e;</td>
</tr>
<tr>
<td>License:</td>
<td><a href="../../licenses/GPL-2">GPL-2</a> | <a href="../../licenses/GPL-3">GPL-3</a> [expanded from: GPL (&ge; 2)]</td>
</tr>
<tr>
<td>NeedsCompilation:</td>
<td>no</td>
</tr>
<tr>
<td>In&nbsp;views:</td>
<td><a href="../../views/Environmetrics.html">Environmetrics</a></td>
</tr>
<tr>
<td>CRAN&nbsp;checks:</td>
<td><a href="../../checks/check_results_Interpol.T.html">Interpol.T results</a></td>
</tr>
</table>
<h4>Downloads:</h4>
<table summary="Package Interpol.T downloads">
<tr>
<td> Reference&nbsp;manual: </td>
<td> <a href="Interpol.T.pdf"> Interpol.T.pdf </a> </td>
</tr>
<tr>
<td> Package&nbsp;source: </td>
<td> <a href="../../../src/contrib/Interpol.T_2.1.1.tar.gz"> Interpol.T_2.1.1.tar.gz </a> </td>
</tr>
<tr>
<td> Windows&nbsp;binaries: </td>
<td> r-devel: <a href="../../../bin/windows/contrib/4.1/Interpol.T_2.1.1.zip">Interpol.T_2.1.1.zip</a>, r-release: <a href="../../../bin/windows/contrib/4.0/Interpol.T_2.1.1.zip">Interpol.T_2.1.1.zip</a>, r-oldrel: <a href="../../../bin/windows/contrib/3.6/Interpol.T_2.1.1.zip">Interpol.T_2.1.1.zip</a> </td>
</tr>
<tr>
<td> macOS&nbsp;binaries: </td>
<td> r-release: <a href="../../../bin/macosx/contrib/4.0/Interpol.T_2.1.1.tgz">Interpol.T_2.1.1.tgz</a>, r-oldrel: <a href="../../../bin/macosx/el-capitan/contrib/3.6/Interpol.T_2.1.1.tgz">Interpol.T_2.1.1.tgz</a> </td>
</tr>
<tr>
<td> Old&nbsp;sources: </td>
<td> <a href="https://CRAN.R-project.org/src/contrib/Archive/Interpol.T"> Interpol.T archive </a> </td>
</tr>
</table>
<h4>Linking:</h4>
<p>Please use the canonical form
<a href="https://CRAN.R-project.org/package=Interpol.T"><samp>https://CRAN.R-project.org/package=Interpol.T</samp></a>
to link to this page.</p>
</body>
</html>
