<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>CRAN - Package RcmdrPlugin.HH</title>
<link rel="stylesheet" type="text/css" href="../../CRAN_web.css" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="DC.identifier" content="https://CRAN.R-project.org/package=RcmdrPlugin.HH" />
<meta name="DC.publisher" content="Comprehensive R Archive Network (CRAN)" />
<meta name="og:title" content="RcmdrPlugin.HH: Rcmdr Support for the HH Package" />
<meta name="og:description" content="Rcmdr menu support for many of the functions in the HH package. The focus is on menu items for functions we use in our introductory courses." />
<meta name="og:image" content="https://CRAN.R-project.org/CRANlogo.png" />
<meta name="og:type" content="website" />
<meta name="og:url" content="https://CRAN.R-project.org/package=RcmdrPlugin.HH" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@_R_Foundation" />
<style type="text/css">
  table td { vertical-align: top; }
</style>
</head>
<body>
<h2>RcmdrPlugin.HH: Rcmdr Support for the HH Package</h2>
<p>Rcmdr menu support for many of the functions in the HH package.
        The focus is on menu items for functions we use in our introductory
        courses.</p>
<table summary="Package RcmdrPlugin.HH summary">
<tr>
<td>Version:</td>
<td>1.1-47</td>
</tr>
<tr>
<td>Depends:</td>
<td>R (&ge; 3.0.2), <a href="../HH/index.html">HH</a></td>
</tr>
<tr>
<td>Imports:</td>
<td><a href="../Rcmdr/index.html">Rcmdr</a> (&ge; 2.0-0), <a href="../lattice/index.html">lattice</a>, <a href="../mgcv/index.html">mgcv</a></td>
</tr>
<tr>
<td>Published:</td>
<td>2018-05-10</td>
</tr>
<tr>
<td>Author:</td>
<td>Richard M. Heiberger, with contributions from Burt Holland</td>
</tr>
<tr>
<td>Maintainer:</td>
<td>Richard M. Heiberger  &#x3c;&#x72;&#x6d;&#x68;&#x20;&#x61;&#x74;&#x20;&#x74;&#x65;&#x6d;&#x70;&#x6c;&#x65;&#x2e;&#x65;&#x64;&#x75;&#x3e;</td>
</tr>
<tr>
<td>License:</td>
<td><a href="../../licenses/GPL-2">GPL-2</a> | <a href="../../licenses/GPL-3">GPL-3</a> [expanded from: GPL (&ge; 2)]</td>
</tr>
<tr>
<td>NeedsCompilation:</td>
<td>no</td>
</tr>
<tr>
<td>CRAN&nbsp;checks:</td>
<td><a href="../../checks/check_results_RcmdrPlugin.HH.html">RcmdrPlugin.HH results</a></td>
</tr>
</table>
<h4>Downloads:</h4>
<table summary="Package RcmdrPlugin.HH downloads">
<tr>
<td> Reference&nbsp;manual: </td>
<td> <a href="RcmdrPlugin.HH.pdf"> RcmdrPlugin.HH.pdf </a> </td>
</tr>
<tr>
<td> Package&nbsp;source: </td>
<td> <a href="../../../src/contrib/RcmdrPlugin.HH_1.1-47.tar.gz"> RcmdrPlugin.HH_1.1-47.tar.gz </a> </td>
</tr>
<tr>
<td> Windows&nbsp;binaries: </td>
<td> r-devel: <a href="../../../bin/windows/contrib/4.1/RcmdrPlugin.HH_1.1-47.zip">RcmdrPlugin.HH_1.1-47.zip</a>, r-release: <a href="../../../bin/windows/contrib/4.0/RcmdrPlugin.HH_1.1-47.zip">RcmdrPlugin.HH_1.1-47.zip</a>, r-oldrel: <a href="../../../bin/windows/contrib/3.6/RcmdrPlugin.HH_1.1-47.zip">RcmdrPlugin.HH_1.1-47.zip</a> </td>
</tr>
<tr>
<td> macOS&nbsp;binaries: </td>
<td> r-release: <a href="../../../bin/macosx/contrib/4.0/RcmdrPlugin.HH_1.1-47.tgz">RcmdrPlugin.HH_1.1-47.tgz</a>, r-oldrel: <a href="../../../bin/macosx/el-capitan/contrib/3.6/RcmdrPlugin.HH_1.1-47.tgz">RcmdrPlugin.HH_1.1-47.tgz</a> </td>
</tr>
<tr>
<td> Old&nbsp;sources: </td>
<td> <a href="https://CRAN.R-project.org/src/contrib/Archive/RcmdrPlugin.HH"> RcmdrPlugin.HH archive </a> </td>
</tr>
</table>
<h4>Reverse dependencies:</h4>
<table summary="Package RcmdrPlugin.HH reverse dependencies">
<tr>
<td>Reverse&nbsp;suggests:</td>
<td><a href="../HH/index.html">HH</a></td>
</tr>
</table>
<h4>Linking:</h4>
<p>Please use the canonical form
<a href="https://CRAN.R-project.org/package=RcmdrPlugin.HH"><samp>https://CRAN.R-project.org/package=RcmdrPlugin.HH</samp></a>
to link to this page.</p>
</body>
</html>
