<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>CRAN - Package RcmdrPlugin.MA</title>
<link rel="stylesheet" type="text/css" href="../../CRAN_web.css" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="DC.identifier" content="https://CRAN.R-project.org/package=RcmdrPlugin.MA" />
<meta name="DC.publisher" content="Comprehensive R Archive Network (CRAN)" />
<meta name="og:title" content="RcmdrPlugin.MA: Graphical User Interface for Conducting Meta-Analyses in R" />
<meta name="og:description" content="Easy to use interface for conducting meta-analysis in R. This package is an Rcmdr-plugin, which allows the user to conduct analyses in a menu-driven, graphical user interface environment (e.g., CMA, SPSS). It uses recommended procedures as described in The Handbook of Research Synthesis and Meta-Analysis (Cooper, Hedges, &amp;amp; Valentine, 2009)." />
<meta name="og:image" content="https://CRAN.R-project.org/CRANlogo.png" />
<meta name="og:type" content="website" />
<meta name="og:url" content="https://CRAN.R-project.org/package=RcmdrPlugin.MA" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@_R_Foundation" />
<style type="text/css">
  table td { vertical-align: top; }
</style>
</head>
<body>
<h2>RcmdrPlugin.MA: Graphical User Interface for Conducting Meta-Analyses in R</h2>
<p>Easy to use interface for conducting meta-analysis in R. This
    package is an Rcmdr-plugin, which allows the user to conduct analyses in a
    menu-driven, graphical user interface environment (e.g., CMA, SPSS). It
    uses recommended procedures as described in The Handbook of Research
    Synthesis and Meta-Analysis (Cooper, Hedges, &amp; Valentine, 2009).</p>
<table summary="Package RcmdrPlugin.MA summary">
<tr>
<td>Version:</td>
<td>0.0-2</td>
</tr>
<tr>
<td>Depends:</td>
<td>R (&ge; 2.15)</td>
</tr>
<tr>
<td>Imports:</td>
<td><a href="../Rcmdr/index.html">Rcmdr</a>, <a href="../MAd/index.html">MAd</a>, <a href="../metafor/index.html">metafor</a></td>
</tr>
<tr>
<td>Suggests:</td>
<td><a href="../knitr/index.html">knitr</a>, <a href="../rmarkdown/index.html">rmarkdown</a>, <a href="../compute.es/index.html">compute.es</a>, <a href="../ggplot2/index.html">ggplot2</a>, <a href="../gridExtra/index.html">gridExtra</a>, <a href="../scales/index.html">scales</a></td>
</tr>
<tr>
<td>Published:</td>
<td>2014-09-21</td>
</tr>
<tr>
<td>Author:</td>
<td>A. C. Del Re</td>
</tr>
<tr>
<td>Maintainer:</td>
<td>A. C. Del Re  &#x3c;&#x61;&#x63;&#x64;&#x65;&#x6c;&#x72;&#x65;&#x20;&#x61;&#x74;&#x20;&#x67;&#x6d;&#x61;&#x69;&#x6c;&#x2e;&#x63;&#x6f;&#x6d;&#x3e;</td>
</tr>
<tr>
<td>License:</td>
<td><a href="../../licenses/GPL-2">GPL-2</a></td>
</tr>
<tr>
<td>URL:</td>
<td><a href="http://acdelre.weebly.com/">http://acdelre.weebly.com/</a></td>
</tr>
<tr>
<td>NeedsCompilation:</td>
<td>no</td>
</tr>
<tr>
<td>Citation:</td>
<td><a href="citation.html">RcmdrPlugin.MA citation info</a> </td>
</tr>
<tr>
<td>Materials:</td>
<td><a href="README.html">README</a> <a href="NEWS">NEWS</a> </td>
</tr>
<tr>
<td>In&nbsp;views:</td>
<td><a href="../../views/MetaAnalysis.html">MetaAnalysis</a></td>
</tr>
<tr>
<td>CRAN&nbsp;checks:</td>
<td><a href="../../checks/check_results_RcmdrPlugin.MA.html">RcmdrPlugin.MA results</a></td>
</tr>
</table>
<h4>Downloads:</h4>
<table summary="Package RcmdrPlugin.MA downloads">
<tr>
<td> Reference&nbsp;manual: </td>
<td> <a href="RcmdrPlugin.MA.pdf"> RcmdrPlugin.MA.pdf </a> </td>
</tr>
<tr>
<td> Package&nbsp;source: </td>
<td> <a href="../../../src/contrib/RcmdrPlugin.MA_0.0-2.tar.gz"> RcmdrPlugin.MA_0.0-2.tar.gz </a> </td>
</tr>
<tr>
<td> Windows&nbsp;binaries: </td>
<td> r-devel: <a href="../../../bin/windows/contrib/4.1/RcmdrPlugin.MA_0.0-2.zip">RcmdrPlugin.MA_0.0-2.zip</a>, r-release: <a href="../../../bin/windows/contrib/4.0/RcmdrPlugin.MA_0.0-2.zip">RcmdrPlugin.MA_0.0-2.zip</a>, r-oldrel: <a href="../../../bin/windows/contrib/3.6/RcmdrPlugin.MA_0.0-2.zip">RcmdrPlugin.MA_0.0-2.zip</a> </td>
</tr>
<tr>
<td> macOS&nbsp;binaries: </td>
<td> r-release: <a href="../../../bin/macosx/contrib/4.0/RcmdrPlugin.MA_0.0-2.tgz">RcmdrPlugin.MA_0.0-2.tgz</a>, r-oldrel: <a href="../../../bin/macosx/el-capitan/contrib/3.6/RcmdrPlugin.MA_0.0-2.tgz">RcmdrPlugin.MA_0.0-2.tgz</a> </td>
</tr>
<tr>
<td> Old&nbsp;sources: </td>
<td> <a href="https://CRAN.R-project.org/src/contrib/Archive/RcmdrPlugin.MA"> RcmdrPlugin.MA archive </a> </td>
</tr>
</table>
<h4>Linking:</h4>
<p>Please use the canonical form
<a href="https://CRAN.R-project.org/package=RcmdrPlugin.MA"><samp>https://CRAN.R-project.org/package=RcmdrPlugin.MA</samp></a>
to link to this page.</p>
</body>
</html>
